-- 동물 ID, 이름
-- 입양 간 기록 o, 보호소 들어온 기록 x인
-- ORDER BY 동물 ID

SELECT O.ANIMAL_ID, O.NAME
FROM ANIMAL_INS I
RIGHT JOIN ANIMAL_OUTS O
ON I.ANIMAL_ID = O.ANIMAL_ID
WHERE I.ANIMAL_ID IS NULL
ORDER BY O.ANIMAL_ID;