-- 식품
-- 식품-주문
-- 생산일자 2022.05
-- 식품 ID, 식품 이름, 총매출
-- 총매출 DESC, 식품 ID ASC

SELECT p.PRODUCT_ID, p.PRODUCT_NAME, p.PRICE * SUM(AMOUNT) AS '총매출'
FROM FOOD_PRODUCT p
JOIN FOOD_ORDER o
ON p.PRODUCT_ID = o.PRODUCT_ID
WHERE o.PRODUCE_DATE BETWEEN '2022-05-01' AND '2022-05-31'
GROUP BY p.PRODUCT_ID
HAVING SUM(o.AMOUNT)
ORDER BY p.PRICE * SUM(AMOUNT) DESC, p.PRODUCT_ID;