-- CATEGORY = 경제
-- 도서 ID, 저자명, 출판일
-- 출판일 기준 ASC

SELECT B.BOOK_ID, A.AUTHOR_NAME, DATE_FORMAT(B.PUBLISHED_DATE, "%Y-%m-%d") AS PUBLISHED_DATE
FROM BOOK B
JOIN AUTHOR A
ON B.AUTHOR_ID = A.AUTHOR_ID
WHERE CATEGORY = '경제'
ORDER BY DATE_FORMAT(B.PUBLISHED_DATE, "%Y-%m-%d");